// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqiunxozogytbipfgmxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxaXVueG96b2d5dGJpcGZnbXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTEzNjAsImV4cCI6MjA2NTgyNzM2MH0.Xq9OQ2lLZkEyNqZzkQ_u17RqUXz7Vo4OdS4V76lFjj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);